# Generated by Django 6.1.1 on 2026-09-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=25),
        ),
    ]
