# Generated by Django 6.1.1 on 2026-09-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_alter_student_s_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_qty', models.IntegerField()),
                ('p_price', models.FloatField()),
            ],
        ),
    ]
