name=input("Enter Account Holder Name:")
age=int(input("Enter your Age:"))
acNo=input("Enter Account Number:")
bal=float(input("Enter Balance:"))
city=input("Enter your City:")
print("===============================")
print("\tBank Account")
print("===============================")
print("Name",name,sep=" : ")
print("Age",age,sep=" : ")
print("Account No.",acNo,sep=" : ")
print("Balance",bal,sep=" : ")
print("City",city,sep=" : ")