# Generated by Django 6.1.1 on 2026-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=30)),
                ('b_author', models.CharField(max_length=30)),
                ('b_price', models.IntegerField()),
            ],
        ),
    ]
