# Generated by Django 6.1.1 on 2026-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.FloatField()),
                ('p_qty', models.IntegerField()),
                ('p_category', models.CharField(max_length=100)),
                ('p_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
